### PR TITLE
[WALL-12550]: Updates check to ensure event origin matches location origin

### PR DESCRIPTION
**Pull request by AMITGOELNY**
### _Summary_
Updates check to ensure event origin matches location origin

### _How did you test your changes?_
manually

### CODE REVIEW

**Review by cb-jake — COMMENTED** [review]
lgtm. We should add a test case for the first check in the if block.

**Comment by AMITGOELNY** [comment]
> lgtm. We should add a test case for the first check in the if block.

Test case added and broken tests resolved

**Review by erin-at-work — APPROVED** [review]

**Comment by Riani837** [comment]
Master

**Review by 01SMD — COMMENTED** [review]
.

**Pull request merged**
