### PR TITLE
Remove in-memory addresses var in WalletLinkProvider

### PR DESCRIPTION
**Pull request by gareys-cb**

### CODE REVIEW

**Comment by bangtoven** [comment]
@gareys-cb are you working on this?

**Comment by gareys-cb** [comment]
> @gareys-cb are you working on this?

@bangtoven I'll review this and see if it is necessary. It's been a while.

**Review by BillyBrooks — COMMENTED** [review]
[]() #
Duplicate of #

>  @`[]() 
[bitcoin.pdf](https://github.com/coinbase/coinbase-wallet-sdk/files/9604238/bitcoin.pdf)
`

**Comment by bangtoven** [comment]
closing it since it's been inactive for 180+ days. please reopen if needed.

**Comment by bangtoven** [comment]
closing it since it's been inactive for 180+ days. please reopen if needed.

**Pull request closed without merging**
