### PR TITLE
Update walletlink

### PR DESCRIPTION
**Pull request by erin-at-work**
Update public walletlink

### CODE REVIEW

**Review by allen-at-work — APPROVED** [review]

**Comment by erin-at-work** [comment]
@vishnumad

**Review by brendanww — APPROVED** [review]

**Comment by warrior7474** [comment]
erin-at-work:erin/walletlink-changes

**Comment by warrior7474** [comment]
> Update public walletlink

**Comment by CRodrigo210** [comment]
[]()👍thanks you so much

**Comment by mikehunter1990** [comment]
What this

**Comment by MorenoMcreeynner** [comment]
> Update public walletlink

**Pull request merged**
