### PR TITLE
Add testapp page for testing new config values

### PR DESCRIPTION
**Pull request by cb-jake**
### _Summary_

Add testapp page for testing new config values

image

image

### _How did you test your changes?_

1. Start the dev server from the root. `yarn dev`
2. visit http://localhost:3001/config
3. Place a log inside the CoinbaseWalletProvider and verify the preferences are set.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by eric-ships — APPROVED** [review]
Thanks for adding the functionality to test config values, @cb-jake ! Approved, pending the "how this was tested" is filled out.

**Comment by cb-jake** [comment]
Thanks @eric-ships Update the docs to test. As testing evolves I'll continue to update how to test.

**Review by fan-zhang-sv — APPROVED** [review]
LGTM

**Pull request merged**
