### PR TITLE
Create SECURITY.mdcreep

### PR DESCRIPTION
**Pull request by Twan1409**

### CODE REVIEW

**Review by alizeguerra — APPROVED** [review]

**Comment by Kayla110** [comment]
Ok

**Comment by Asli71** [comment]
Ini apa jualanya ?

**Review by hoseainyazdani1371 — APPROVED** [review]
>

**Review by mrcali213 — APPROVED** [review]

**Comment by kingclowndean** [comment]
www.nakedclowncalendar.com/

**Pull request closed without merging**
