### PR TITLE
ensures address string & normalizes letter case on addresses read from cache

### PR DESCRIPTION
**Pull request by belfz**
Fixes an issue detected and described in [#149](https://github.com/walletlink/walletlink/issues/149).

### CODE REVIEW

**Comment by majcherpiotrek** [comment]
Would be really helpful to merge this soon 🙏 Facing the same issue

**Comment by belfz** [comment]
cc @petejkim @hieronymus777

**Comment by sunguru98** [comment]
One of our projects has relied on the wallet link and it would really be nice if this gets approved sooner .. Facing the same issue as well.

**Comment by albanbleicher** [comment]
Would be really glad if this PR could be merged soon ! 
Thanks ! 🙏

**Comment by Hlllllllii** [comment]
✌️✍️🙏


Sent from Yahoo Mail for iPhone


On Thursday, September 9, 2564, 2:12 AM, Alban Bleicher ***@***.***> wrote:




Would be really glad if this PR could be merged soon !
Thanks ! 🙏

**Comment by belfz** [comment]
@petejkim @hieronymus777 pinging you again for this, could you please review & merge this pull request?

**Comment by willishq** [comment]
> @petejkim @hieronymus777 pinging you again for this, could you please review & merge this pull request?

just adding a +1 for this.

**Comment by ryan22271** [comment]
I didn’t set this up for myself I’m not a coder or programmer I’m being hacked by you all so don’t tell me to fix it you all are thieves and I just don’t like u or what’s been happening 


Sent from ME


On Wednesday, September 22, 2021, 1:57 PM, Oilking777 ***@***.***> wrote:



Hey is there any way we can talk on phone?


Sent from Yahoo Mail for iPhone


On Wednesday, September 22, 2021, 7:05 AM, Andrew Willis ***@***.***> wrote:





@petejkim @hieronymus777 pinging you again for this, could you please review & merge this pull request?


just adding a +1 for this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amaurer** [comment]
I ran into this same issue, tested this change in my code - worked perfectly.  Let's get it merged please.

**Comment by bangtoven** [comment]
thank you. this has been resolved with https://github.com/coinbase/coinbase-wallet-sdk/pull/315/files

**Pull request closed without merging**
