### PR TITLE
Sync check unseen events changes with master

### PR DESCRIPTION
**Pull request by vishnumad**
### _Summary_
5eb5e712a0426fec10a45475c6779cd2aa5da218
e6dac1d9274ca887abf03cfa8cb40df7364e121c

### CODE REVIEW

**Review by bangtoven — APPROVED** [review]

**Review by bangtoven — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for bangtoven @ 2023-08-29 19:57:54 UTC
User cannot review their own commit

**Review by bangtoven — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for bangtoven @ 2023-08-29 19:58:25 UTC
User cannot review their own commit

**Review by bangtoven — APPROVED** [review]

**Review by bangtoven — APPROVED** [review]

**Review by bangtoven — APPROVED** [review]

**Review by bangtoven — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for bangtoven @ 2023-08-29 20:40:33 UTC
User cannot review their own commit

**Comment by cb-heimdall** [comment]
Review Error for bangtoven @ 2023-08-29 20:42:30 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by cb-heimdall** [comment]
Review Error for bangtoven @ 2023-08-29 20:50:48 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Pull request merged**
